-- DROP
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;

-- CREATE 
CREATE TABLE PROFESSOR(
    PRO_NO    VARCHAR2(10 BYTE) NOT NULL,
    PRO_NAME  VARCHAR2(20 BYTE) NULL, 
    PRO_MAJOR VARCHAR2(20 BYTE) NULL
);

CREATE TABLE COURSE(
    COUR_NO   NUMBER(5) NOT NULL,
    COUR_NAME VARCHAR2(20 BYTE) NOT NULL,
    COUR_SCR  NUMBER(3) NULL
);

CREATE TABLE STUDENT (
    STU_NO      VARCHAR2(10 BYTE)  NOT NULL,
    STU_NAME    VARCHAR2(20 BYTE)  NOT NULL,
    STU_ADDR    VARCHAR2(100 BYTE) NULL,
    STU_GRD     NUMBER(1)          NULL,
    PRO_NO      VARCHAR2(30 BYTE)  NOT NULL
);

CREATE TABLE ENROLL(
    ENR_NO   NUMBER(5)          NOT NULL,
    STU_NO   VARCHAR2(10 BYTE)  NOT NULL,
    COUR_NO  NUMBER(5)          NOT NULL,
    ENR_DATE DATE               NULL
);

CREATE TABLE LECTURE(
    LECT_NO     NUMBER(5)          NOT NULL,
    PRO_NO      VARCHAR2(10 BYTE)  NOT NULL,
    ENR_NO      NUMBER(5)          NOT NULL,
    LECT_NAME   VARCHAR2(20 BYTE)  NULL,
    LECT_PLACE  VARCHAR2(30 BYTE)  NULL
);

-- ALTER TABLE (PK)
ALTER TABLE PROFESSOR 
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE 
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NO);
ALTER TABLE STUDENT 
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE ENROLL 
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LECT_NO);
    
-- ALTER TABLE (FK)
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(PRO_NO)
        REFERENCES PROFESSOR(PRO_NO)
            ON DELETE CASCADE;
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO)
        REFERENCES STUDENT(STU_NO)
            ON DELETE SET NULL;
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COUR_NO)
        REFERENCES COURSE(COUR_NO)
            ON DELETE SET NULL;
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PRO_NO)
        REFERENCES PROFESSOR(PRO_NO) 
            ON DELETE CASCADE;
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO)
        REFERENCES ENROLL(ENR_NO) 
            ON DELETE CASCADE;





